
services:
  service:
    build:
      context: .
    volumes:
      - .:/app/
    container_name: app
    command: ["sh", "-c", "until nc -zv pg_db 5432; do sleep 60; done; /app/start.sh"]
    expose:
      - "8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - pg_db

  pg_db:
    image: postgres:16.0
    container_name: pg_db
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/data_dump.sql

  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    depends_on:
      - pg_db
    restart: always
