
services:
  service:
    build:
      context: app
    command: ["sh", "-c", "until nc -zv theatre-db 5432; do sleep 1; done; ./run_uwsgi.sh"]
    expose:
      - "8000"
    env_file:
      - .env  # ./.env
    volumes:
      - ./data:/var/www/static  # mount dir for static
    restart: always
    depends_on:
      - theatre-db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/var/www/static  # mount dir for static
    depends_on:
      - service
    ports:
      - "80:80"
    restart: always

  theatre-db:
    image: postgres:16.0
    container_name: postgresdb
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  elastick:
    image: elasticsearch:8.6.2
    container_name: elastick
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    depends_on:
      - theatre-db
    restart: always
